### ISSUE TITLE
Gmail app password exposed

### ISSUE THREAD

**Issue by ashikdnd** [Suryaa07/LTTS_Webpage#1]
Your gmail authentication credentials may be badly misused. Move the credentials to .env file and add .env to .gitignore

**Comment by Suryaa07** [comment]
I have changed it as per your instructions sir. If possible do ping me whether it is okay. 
Thank you

**Comment by ashikdnd** [comment]
That's good. You may also move your host to env APP_HOST=http://localhost:3000 if you are planning to use the host in several places.

**Comment by Suryaa07** [comment]
Thank you so much for your corrections sir.
